spring:
  application:
    name: payment-service
  datasource:
    password: mysql
    url: jdbc:mysql://localhost:3306/bookmyshow?createDatabaseIfNotExist=true&autoReconnect=true
    username: root
   
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:    
      hibernate:
         dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    
server:
  port: ${PORT:0}
eureka:
  instance:
    instanceId: ${spring.cloud.client.hostname}:${spring.application.name}:${random.int[1,999999]}
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}

management:
  endpoints.web.exposure.include: '*'
  endpoint.shutdown.enabled: true